language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby
gemfile:
  - Gemfile32
  - Gemfile
services:
  - memcache
  - mysql
matrix:
  allow_failures:
    - rvm: jruby
before_script:
  - mysql -e 'create database identity_cache_test'
