language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
gemfile:
  - Gemfile
  - Gemfile.rails4
services:
  - memcache
  - mysql
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: 2.1.0
before_script:
  - mysql -e 'create database identity_cache_test'
