language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

gemfile:
  - Gemfile32
  - Gemfile
  - Gemfile.rails41

env:
  - DB=mysql2
  - DB=postgresql

services:
  - memcache
  - mysql

sudo: false

before_script:
  - mysql -e 'create database identity_cache_test'
  - psql -c 'create database identity_cache_test;' -U postgres
