language: ruby

rvm:
  - '2.2.6'
  - '2.4.1'

gemfile:
  - Gemfile.rails42
  - Gemfile.rails50
  - Gemfile.rails51

matrix:
  exclude:
    - gemfile: Gemfile.rails50
      env: DB=postgresql
    - gemfile: Gemfile.rails51
      env: DB=postgresql

env:
  - DB=mysql2
  - DB=postgresql

services:
  - memcache
  - mysql

sudo: false

before_script:
  - mysql -e 'create database identity_cache_test'
  - psql -c 'create database identity_cache_test;' -U postgres

cache: bundler
