language: ruby

rvm:
  - 2.1
  - 2.2.3

gemfile:
  - Gemfile.rails40
  - Gemfile.rails41
  - Gemfile.rails42
  - Gemfile.rails5

env:
  - DB=mysql2
  - DB=postgresql

services:
  - memcache
  - mysql

matrix:
  exclude:
    - rvm: 2.1
      gemfile: Gemfile.rails5

sudo: false

before_script:
  - mysql -e 'create database identity_cache_test'
  - psql -c 'create database identity_cache_test;' -U postgres
